esphome:
  name: rpi-pico2

rp2040:
  board: rpipicow
  framework:
    platform_version: https://github.com/maxgerhardt/platform-raspberrypi.git

wifi:
  ssid:  !secret wifi_ssid
  password:  !secret wifi_password
  fast_connect: True
  power_save_mode: NONE
# Optional manual IP
  manual_ip:
    static_ip: !secret ip_pico2
    gateway: !secret ip_gw
    subnet: !secret ip_subnet
    dns1: !secret ip_dns1
    dns2: !secret ip_dns2

# Enable logging
logger:
  level: DEBUG
  #baud_rate: 0 # disable logging over uart
  
# Enable Home Assistant API
api:

  # encryption:
  #   key: !secret encryption_key
    
ota:
  password: !secret ota_password

# uart:
#   id: uart_0
#   tx_pin: 
#     number: 0
#   rx_pin:
#     number: 1
#     #inverted: true
#   baud_rate: 115200


sensor:
- platform: uptime
  name: "esp-p1reader Uptime"
- platform: wifi_signal
  name: "esp-p1reader Wi-Fi Signal"
  update_interval: 60s

# light:
#   - platform: rgb
#     name: RGB
#     red: r
#     green: g
#     blue: b

# output:
#   - platform: rp2040_pwm
#     id: r
#     pin: 2
#   - platform: rp2040_pwm
#     id: g
#     pin: 3
#   - platform: rp2040_pwm
#     id: b
#     pin: 4

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "esp-p1reader IP Address"
    ssid:
      name: "esp-p1reader Wi-Fi SSID"
    bssid:
      name: "esp-p1reader Wi-Fi BSSID"
  - platform: version
    name: "ESPHome Version"
    hide_timestamp: false